In [55]:
import torch.distributions as tdist
import torch

In [56]:
x = torch.tensor([[[0,0],[0,0.1]]])

In [60]:
j = 3
n = tdist.Normal(loc=torch.tensor([0.]), scale=torch.tensor([1.]))
shape = list(x.shape)
shape[0] = j
eps = n.sample(shape).reshape(shape)

In [61]:
x.shape

torch.Size([1, 2, 2])

In [62]:
x

tensor([[[0.0000, 0.0000],
         [0.0000, 0.1000]]])

In [63]:
x = x + eps.reshape(shape)

In [64]:
x

tensor([[[ 0.6485,  1.3806],
         [ 0.3300,  0.0389]],

        [[ 0.7668,  0.8896],
         [ 0.9087, -0.0348]],

        [[ 0.5833, -3.1615],
         [ 0.4411,  0.0646]]])

In [65]:
eps

tensor([[[ 0.6485,  1.3806],
         [ 0.3300, -0.0611]],

        [[ 0.7668,  0.8896],
         [ 0.9087, -0.1348]],

        [[ 0.5833, -3.1615],
         [ 0.4411, -0.0354]]])

In [69]:
x.mean(dim=0)

tensor([[ 0.6662, -0.2971],
        [ 0.5599,  0.0229]])